### ISSUE TITLE
duplicated function 'sigmoid'

### ISSUE THREAD

**Issue by lilweege** [BornaSadeghi/Spooki-Neural-Network-Library#1]
https://github.com/BornaSadeghi/Spooki-Neural-Network-Library/blob/55710117bfd21a2d025544ee8e2321b425c2329f/NeuralNetwork/nn.py#L14
https://github.com/BornaSadeghi/Spooki-Neural-Network-Library/blob/55710117bfd21a2d025544ee8e2321b425c2329f/NeuralNetwork/activations.py#L6

the function is unused within nn.py anyways, it should not exist there regardless

**Comment by BornaSadeghi** [comment]
Thanks my man  w  e  e  g  i  e   dbe8bd56981fa6d421aea933beae8095990bc11f
